export const questions = {
  accounting: [
    "Payment Frequency",
    "Autopay",
    "Email for Submitting Invoices",
    "Payment Type",
    "Payment Portal",
    "Portal URL",
    "PO's Required?",
    "PO's Required for Invoices?",
    "Approval's Required?",
    "Have you attached the contract?",
    "Contact Name",
    "Contact Phone",
    "Contact Email",
    "Notes",
  ],
  cabinets: [
    "Are Substitutions Allowed?",
    "Preferred Colors",
    "Preferred Style",
    "Overlay",
    "Preferences on Crown",
    "Bid Type Preferences",
    "Upper Cabinet Standard Specs.",
    "Vanity Height Standard Specs.",
    "Is Soft Close Standard?",
    "Any Areas Optioned Out?",
    "Notes"
  ],
  carpet: [
    "Are Substitutions Allowed?",
    "Preferred Padding Brand",
    "Who Will be Doing Takeoffs?",
    "Waste Factor Percentage",
    "Notes"
  ],
  countertops: [
    "Are Substitutions Allowed?",
    "Preferred Material Thickness",
    "Preferred Edge",
    "Waterfall Sides - Standard or Option?",
    "Faucet Holes?",
    "Stove Range Specifications",
    "Who Will be Doing Takeoffs?",
    "Waste Factor Percentage",
    "Notes"
  ],
  expediting: [
    "Is there a vendor portal?",
    "Vendor Portal URL",
    "Has the Vendor Portal Account been created?",
    "Portal Username",
    "Portal Password",
    "How are jobs released?",
    "PO Correction Handling?",
    "Estimated Number of Homes per Year",
    "Estimated Start Date",
    "Is the client using the In-House Program?",
    "Notes"
  ],
  tile: [
    "Are Substitutions Allowed?",
    "Floor Setting Material",
    "Floor Custom Setting Material",
    "Wall Setting Material",
    "Wall Custom Setting Material",
    "Alotted Float",
    "Charge for Extra Float",
    "Waterproofing Method",
    "Waterproofing Method - Shower Floor",
    "Waterproofing Method - Shower Walls",
    "Waterproofing Method - Tub Wall",
    "Who is installing fiberglass?",
    "Will we be installing backerboard?",
    "Punch Out Material",
    "Shower Niche Construction",
    "Shower Niche Framing",
    "Preformed Shower Niche Brand",
    "Are Corner Soap Dishes Standard?",
    "Corner Soap Dish Material",
    "Shower Seat Construction",
    "Metal Edge Options",
    "Grout Joint Sizing",
    "Grout Joint Notes",
    "Preferred Grout Brand",
    "Upgraded Grout and Formula",
    "Grout Product",
    "Subfloor Std. Practice",
    "Subfloor Products",
    "Wall Tile Height Standard",
    "Who Will be Doing Takeoffs?",
    "Waste Factor Percentage",
    "Waste Factor Percentage - Walls",
    "Waste Factor Percentage - Floors",
    "Waste Factor Percentage - Mosaics",
    "Notes"
  ],
  woodVinyl: [
    "Are Substitutions Allowed?",
    "Preferred Glue Products",
    "Other Glue Product",
    "Stain or Primed?",
    "Are Transition Strips Standard Practice?",
    "HVAC Requirement?",
    "MC Surfaces Install Wood Trim?",
    "2nd Story Subfloor Construction",
    "Who Will be Doing Takeoffs?",
    "Waste Factor Percentage",
    "Notes"
  ]
}

export const tableHeaders = {
  addresses: ["Type", "Street Address", "City", "State", "Zip"],
  contacts: ["Name", "Title", "Phone", "Email"],
  files: [],
  programs: ["Chosen Selections"],
  approvals: []
};

export const statusColors = {
  Potential: "#1A5276",
  Queued: "#F4D03F",
  Approved: "#3498DB",
  Declined: "#E74C3C",
  Pushed: "#58D68D",
};